// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using PunishmentPointsApp.Repositories;
using System;

namespace PunishmentPointsApp.Migrations
{
    [DbContext(typeof(PunishmentContext))]
    partial class PunishmentContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125");

            modelBuilder.Entity("PunishmentPointsApp.Models.Punishment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AuthorId");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("date");

                    b.Property<string>("Reason");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.ToTable("Punishments");
                });

            modelBuilder.Entity("PunishmentPointsApp.Models.TeamMember", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.Property<int?>("PunishmentId");

                    b.HasKey("Id");

                    b.HasIndex("PunishmentId");

                    b.ToTable("TeamMembers");
                });

            modelBuilder.Entity("PunishmentPointsApp.Models.Punishment", b =>
                {
                    b.HasOne("PunishmentPointsApp.Models.TeamMember", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId");
                });

            modelBuilder.Entity("PunishmentPointsApp.Models.TeamMember", b =>
                {
                    b.HasOne("PunishmentPointsApp.Models.Punishment")
                        .WithMany("Recipients")
                        .HasForeignKey("PunishmentId");
                });
#pragma warning restore 612, 618
        }
    }
}
